config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :decks

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/deck.rb
class Deck < ApplicationRecord

  validates :title, presence: true

  has_many :questions
end

app/models/question.rb
class Question < ApplicationRecord
  validates :question_text, presence: true
  belongs_to :deck
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController

  def index
    @decks = Deck.all
  end

  def show
    @deck = Deck.find(params[:id])
  end

  def new
    @deck = Deck.new
  end

  def create
    #render plain: params[:deck].inspect
    @deck = Deck.new(deck_params)

    if @deck.save
      redirect_to @deck
    else
      render 'new'
    end
  end

private
  def deck_params
    params.require(:deck).permit(:title)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/decks/index.html.erb
<h1> Listing All Decks </h1>

  <table>
    <tr>
      <th>Title<th>
    </tr>

    <% @decks.each do |deck| %>
      <tr>
        <td><%= deck.title %></td>
        <td><%= link_to 'Show', deck_path(deck) %></td>
      </tr>
    <% end %>
  </table>

app/views/decks/new.html.erb
<h1> New Deck </h1>

<%= form_with scope: :deck, url: decks_path, local: true do |form| %>

<% if @deck.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@deck.errors.count, "error") %>
prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @deck.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', decks_path %>

app/views/decks/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @deck.title %>
</p>

<%= link_to 'Back', decks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlashcardsRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to FlashCards!</h1>

<%= link_to "Create a new deck", new_deck_path %>
<br>
<%= link_to 'My Decks', controller: 'decks' %>